FROM python:3-alpine
WORKDIR /app

build:
    # Use Python Wheels to produce package files into /wheels
    RUN pip install wheel
    COPY requirements.txt ./
    RUN pip wheel -r requirements.txt --wheel-dir=wheels
    RUN mkdir src
    COPY main.py src/main.py
    SAVE ARTIFACT src /src
    SAVE ARTIFACT wheels /wheels

docker:
    COPY +build/src src
    COPY +build/wheels wheels
    COPY requirements.txt ./
    RUN pip install --no-index --find-links=wheels -r requirements.txt
    ENV PORT 8080
    ENTRYPOINT ["python", "src/main.py"]
    SAVE IMAGE can/clean_swagger:latest
    ARG GCP_PROJECT
    SAVE IMAGE --push gcr.io/${GCP_PROJECT}/clean_swagger:latest