from can_tools.scrapers.base import CMU, DatasetBase
from can_tools.scrapers.official import (  # IllinoisDemographics,; IllinoisHistorical,; Massachusetts,
    CaliforniaCasesDeaths,
    CaliforniaHospitals,
    CDCCovidDataTracker,
    DCCases,
    DCDeaths,
    DCGeneral,
    Florida,
    FloridaHospitalCovid,
    FloridaHospitalUsage,
    FloridaICUUsage,
    HHSReportedPatientImpactHospitalCapacityFacility,
    HHSReportedPatientImpactHospitalCapacityState,
    NewYorkTests,
    PennsylvaniaCasesDeaths,
    PennsylvaniaHospitals,
    TexasCasesDeaths,
    TexasTests,
    Wisconsin,
)
