from can_tools.scrapers import CMU

crename = {
    "Total Doses Allocated": CMU(
        category="total_vaccine_allocated",
        measurement="cumulative",
        unit="doses",
    ),
    "Vaccine Doses Administered": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
    ),
    "People Vaccinated with at least One Dose": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
    ),
    "People Fully Vaccinated": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
    ),
}

crename_female = {
    "Doses Administered 50-64 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="female",
        age="50-64",
    ),
    "Doses Administered 16-49 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="female",
        age="16-49",
    ),
    "Doses Administered 65-79 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="female",
        age="65-79",
    ),
    "Doses Administered 80+ years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="female",
        age="80_plus",
    ),
    "Doses Administered Unknown": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="female",
        age="unknown",
    ),
    "Doses Administered Total": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="female",
    ),
    "People Vaccinated with at least One Dose 16-49 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="16-49",
    ),
    "People Vaccinated with at least One Dose 50-64 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="50-64",
    ),
    "People Vaccinated with at least One Dose 65-79 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="65-79",
    ),
    "People Vaccinated with at least One Dose 80+ years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="80_plus",
    ),
    "People Vaccinated with at least One Dose Unknown": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="unknown",
    ),
    "People Vaccinated with at least One Dose Total": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="female",
    ),
    "People Fully Vaccinated 16-49 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="16-49",
    ),
    "People Fully Vaccinated 50-64 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="50-64",
    ),
    "People Fully Vaccinated 65-79 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="65-79",
    ),
    "People Fully Vaccinated 80+ years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="80_plus",
    ),
    "People Fully Vaccinated Unknown": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="female",
        age="unknown",
    ),
    "People Fully Vaccinated Total": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="female",
    ),
}

crename_male = {
    "Doses Administered 50-64 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="male",
        age="50-64",
    ),
    "Doses Administered 16-49 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="male",
        age="16-49",
    ),
    "Doses Administered 65-79 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="male",
        age="65-79",
    ),
    "Doses Administered 80+ years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="male",
        age="80_plus",
    ),
    "Doses Administered Unknown": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="male",
        age="unknown",
    ),
    "Doses Administered Total": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="male",
    ),
    "People Vaccinated with at least One Dose 16-49 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="16-49",
    ),
    "People Vaccinated with at least One Dose 50-64 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="50-64",
    ),
    "People Vaccinated with at least One Dose 65-79 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="65-79",
    ),
    "People Vaccinated with at least One Dose 80+ years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="80_plus",
    ),
    "People Vaccinated with at least One Dose Unknown": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="unknown",
    ),
    "People Vaccinated with at least One Dose Total": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="male",
    ),
    "People Fully Vaccinated 16-49 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="16-49",
    ),
    "People Fully Vaccinated 50-64 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="50-64",
    ),
    "People Fully Vaccinated 65-79 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="65-79",
    ),
    "People Fully Vaccinated 80+ years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="80_plus",
    ),
    "People Fully Vaccinated Unknown": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="male",
        age="unknown",
    ),
    "People Fully Vaccinated Total": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="male",
    ),
}

crename_unknown = {
    "Doses Administered 50-64 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="unknown",
        age="50-64",
    ),
    "Doses Administered 16-49 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="unknown",
        age="16-49",
    ),
    "Doses Administered 65-79 years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="unknown",
        age="65-79",
    ),
    "Doses Administered 80+ years": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="unknown",
        age="80_plus",
    ),
    "Doses Administered Unknown": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="unknown",
        age="unknown",
    ),
    "Doses Administered Total": CMU(
        category="total_vaccine_doses_administered",
        measurement="cumulative",
        unit="doses",
        sex="unknown",
    ),
    "People Vaccinated with at least One Dose 16-49 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="16-49",
    ),
    "People Vaccinated with at least One Dose 50-64 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="50-64",
    ),
    "People Vaccinated with at least One Dose 65-79 years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="65-79",
    ),
    "People Vaccinated with at least One Dose 80+ years": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="80_plus",
    ),
    "People Vaccinated with at least One Dose Unknown": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="unknown",
    ),
    "People Vaccinated with at least One Dose Total": CMU(
        category="total_vaccine_initiated",
        measurement="cumulative",
        unit="people",
        sex="unknown",
    ),
    "People Fully Vaccinated 16-49 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="16-49",
    ),
    "People Fully Vaccinated 50-64 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="50-64",
    ),
    "People Fully Vaccinated 65-79 years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="65-79",
    ),
    "People Fully Vaccinated 80+ years": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="80_plus",
    ),
    "People Fully Vaccinated Unknown": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="unknown",
        age="unknown",
    ),
    "People Fully Vaccinated Total": CMU(
        category="total_vaccine_completed",
        measurement="cumulative",
        unit="people",
        sex="unknown",
    ),
}
