name: deploy airflow

# TODO: maybe use on: schedule to sync dags every N hours?
on:
  workflow_dispatch:
  push:
    paths:
      - 'can_tools/**'
      - 'services/airflow/**'
    branches:
      - main
    tags:
      - '*'

jobs:
  rsync_resources:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '318.0.0'
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true
    - name: copy can_tools directory
      run: gsutil rsync -r can_tools gs://${{ secrets.GCP_AIRFLOW_BUCKET }}/dags/can_tools
    - name: copy dags
      run: gsutil rsync services/airflow/dags gs://${{ secrets.GCP_AIRFLOW_BUCKET }}/dags
