name: Test

on:
  push:
    paths:
      - "can_tools/**"
    branches:
      - main
  pull_request:
    paths:
      - "can_tools/**"
    branches:
      - main

env:
  BEA_KEY: ${{ secrets.BEA_KEY }}
  CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run black
          pipenv run test
